### ISSUE TITLE
[UIKit] Provide interface to config the text in UI lib

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/chat-SDK-Android#101]
Currently only text are:

`Send`
Actions's Photo / Camera (is it system or apps?)
`Delivering`
`Some read` / `All Read` / `Unread`
Date of message

**Comment by howawong** [comment]
Message Status, Date Format and  Place holder are completed in #101.

However, there is no "send" action as it is just image button.
Camera & Images from photo gallery are set by system.
