### ISSUE TITLE
[UIKit] Support showing another users' name for conversation title

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/chat-SDK-Android#102]

**Comment by howawong** [comment]
@carmenlau  I forgot the possible or supported types. Can you update the issue with example titles?

**Comment by carmenlau** [comment]
We need to support 2 types, show original conversation name or participants' name with comma separated (exclude current user, so direct conversation should only have 1 name). conversation name is default

**Comment by howawong** [comment]
Do you want ConversationsActivity (list of all conversations) need to support this feature? A currently ConversationsActivity in chat_example but not chat_ui.

**Comment by carmenlau** [comment]
This issue is about ui kit `ConversationActivity` in `chat_ui` allow user to configure so we need to have it.

For `chat_example` `ConversationsActivity`, it only good to have if it is every easy. :)

**Comment by howawong** [comment]
Seems, there is no trivial way as `userCache` in `ConversationView` requires asynchronous  operation to retrieve user display names. But `userCache` is an internal class and not very easy to include `userCache` in chat_example (from demonstration point of view) . So unless we want to include `ConversationsActivity` in UI Kit, otherwise I just leave it at this moment.

**Comment by howawong** [comment]
And also what about push notification, I guess it is out of UI Kit scope though...

**Comment by carmenlau** [comment]
No worries, push notification is just the demo. User can construct any title they like. The hooks have participants, and user can just get the username there, right?

**Comment by howawong** [comment]
Of course, but it will take around 5 - 10 lines.

**Comment by carmenlau** [comment]
I think we will keep it as it

**Comment by carmenlau** [comment]
I think we can keep it as it
