### ISSUE TITLE
[UIKit] Fail to play voice message

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/chat-SDK-Android#106]
In nexus 5x

```
11-22 19:07:40.604 3658-19050/? E/OMXNodeInstance: setConfig(e4a00a5:google.aac.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
```

**Comment by howawong** [comment]
![screen shot 2017-11-23 at 12 21 43 pm](https://user-images.githubusercontent.com/760880/33158914-efaa108a-d048-11e7-9657-a986071aead2.png)


http://localhost:3000//8d80b5d2-95dd-4094-b650-249e9985c2e4-voice-1511410576952.m4a?expiredAt=1511411703&signature=DQkD3kIuNwdHt8v6CGns8dgw4Ubm_YouKJwdrPMQYBA=

get_messages output wrong URL.

**Comment by howawong** [comment]
Hmmm, wait a minute, I need to check further
