### ISSUE TITLE
[Cache] Create and edit message fail handling

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/chat-SDK-Android#129]
After checking the code, found some detail is missing when handling create and edit message fail case.

#### addMessage
- [Sending] Add to cache
- [Success] Mark message in cache alreadySyncToServer
- [Fail] Mark message in cache not alreadySyncToServer and fail

#### editMessage
- [Sending] Update message cache
- [Success] Mark message in cache alreadySyncToServer
- [Fail] Mark message in cache not alreadySyncToServer and fail (Will be overwrite when fetch by server again)

#### deleteMessage
- If message is `fail`, will delete from cache only and return 
- If message is not `fail`, call server delete message api
    - [Sending] Do nothing
    - [Success] Mark message deleted in cache
    - [Fail] Do nothing

#### fetchMessages
- [Cache callback] all alreadySyncToServer and not fail message in cache
- [Server callback] messages from server, update messages to alreadySyncToServer and not fail

#### fetchUnsentMessages
-  not alreadySyncToServer or fail messages in cache, so both add and edit failed messages will be included

### Problem

1. When user call delete on edit failed message, delete message will only delete the message cache. But not calling the server.
2. If user edit message fail, next time when user call fetch message. User will get the edit failed message from `fetchUnsentMessages` api. In `fetchMessages` api, the cache callback will not include the edit failed message, the server callback will include the old version message. This behavior is difficult for developer to handle edit message fail case.

### Discussion
Instead of using 2 flags `alreadySyncToServer` and `fail` to indicate the message sync status, should use enum instead. In the current model, seems we cannot identity the message is add or edited failed message. 

Also for the edit message fail case, it is difficult to handle and explain in the api level (Which version of message should we keep? the edited or old version). After testing on telegram, edit message is a synchronous action, so we decided to update cache only after edit message success. So all the failed message in cache will be add failed message.

#### addMessage
- [Sending] Add to cache
- [Success] Mark message in cache alreadySyncToServer
- [Fail] Mark message in cache fail to add

#### editMessage
- [Sending] Do nothing
- [Success] Update message cache with edit version
- [Fail] Do nothing

#### deleteMessage
- If the message is `fail` (add failed message), will delete from cache only and return 
- If the message is not `fail`, call server delete message api
    - [Sending] Do nothing
    - [Success] Mark message deleted in cache
    - [Fail] Do nothing

#### fetchMessages
- [Cache callback] all alreadySyncToServer message
- [Server callback] messages from server

#### fetchUnsentMessages
-  not alreadySyncToServer or fail messages in cache, should only add failed message

**Comment by chpapa** [comment]
@carmenlau @rickmak 
Why don't we simply have two cache? The message cache, and the operation (add / edit, or even delete if needed) cache. The above behavior looks unnecessarily complicated to me, I can barely put together a mental model of how it works...

If we simply have two caches, the behavior will be as follows which I think it simpler and way more easier to explain?

## Data Structure
* 2 Caches:
    * Operation Cache
    * Message Cache
* Operation Object, three attributes:
    * operation: enum(add, edit, delete)
    * message: message object
    * status: enum(pending, failed)

### addMessage
* [Sending] Add the operation object to operation cache [add, message object, pending]
* [Success] Move the message object to the localMessage cache, delete the operation object
* [Fail] Mark the operation object [add, message object, failed]

### editMessage
* [Sending] Add to operation cache [edit, message object, pending]
* [Success] Replace the message object from operation cache to message cache
* [Fail] Mark the operation object [edit, message object, failed]

### deleteMessage
* [Sending] Add to operation cache [delete, message object, pending]
* [Success] Delete message object and operation object
* [Fail] Mark the operation object [delete, message object, failed]

### fetchMessages
* [Cache callback] all message cache, with message replaced operation object with add / edit, and delete (so a secondary index of message ID is a good idea for the operation cache, but usually operation cache should be small which maybe not relevant...)
* [Server callback] message from server

### fetchUnsentMessages
* Could change it to `fetchFailedMessageOperations`? Which return a list of add/edit/delete operation with the message object.

**Comment by Steven-Chan** [comment]
@chpapa @carmenlau @rickmak 
I think having two caches is good and simple to understand, would like to align some details with you though.

1. `fetchFailedMessageOperations(type, message id)` should be `fetchFailedMessageOperations(type, conversation id)`? I imagine when I want to show failed messages in a conversation, I would call something like `fetchFailedMessageOperations(ADD_OPERATION, conversation_id)`.
1. I think the `retryMessageOperation` is necessary. Imagine when I try to add a new message, and failed, and retry adding the failed message and then failed again. There would be two failed operations for the same message. So it seems its the responsibility of the SDK to provide a retry API.
1.  The message object of the operation object should be a snapshot of the message object when the API is called. So when the retry API is called, the corresponding API (i.e. addMessage/editMessage/deleteMessage) would be called with that snapshot.

**Comment by chpapa** [comment]
> fetchFailedMessageOperations(type, message id) should be fetchFailedMessageOperations(type, conversation id)? I imagine when I want to show failed messages in a conversation, I would call something like fetchFailedMessageOperations(ADD_OPERATION, conversation_id).

Good suggestion. I think how do we query failedMessageOperation need some more thought on the exact use cases. Your suggestion of `(type, conversation id)` definitely make senses. I guess a method to fetch all might be useful too. 

> I think the retryMessageOperation is necessary. Imagine when I try to add a new message, and failed, and retry adding the failed message and then failed again. There would be two failed operations for the same message. So it seems its the responsibility of the SDK to provide a retry API.

Agree, this is to avoid overloading the methods of `addMessage` and `editMessage`

> The message object of the operation object should be a snapshot of the message object when the API is called. So when the retry API is called, the corresponding API (i.e. addMessage/editMessage/deleteMessage) would be called with that snapshot.

Sounds ok to me. Only edge case is the timestamp, not sure in the use case, what timestamp (created_at?) users will expect...

> We did not provide anything similar to cancelMessageOperation in all API. I think this is for deleting a failed operation object only?

Yes

**Comment by Steven-Chan** [comment]
I think the `retryMessageOperation` does not really fit into SDK API styles.

Most SDK API are like `doA(params, callbackA)` and `doB(params, callbackB)`, but the `retryMessageOperation` would be like `do(A, params)`. 

For example, with the message APIs, we have different function signatures for save and delete API, but `retryMessageOperation` would be called for both types of the operations.

**Comment by chpapa** [comment]
> I think the retryMessageOperation does not really fit into SDK API styles.
> 
> Most SDK API are like doA(params, callbackA) and doB(params, callbackB), but the retryMessageOperation would be like do(A, params).
> 
> For example, with the message APIs, we have different function signatures for save and delete API, but retryMessageOperation would be called for both types of the operations.

Hmmm, don't really get it but do you have a proposed way to do it?

**Comment by carmenlau** [comment]
@chpapa Steven means since `add`, `edit` and `delete` api originally have different type of callback. So we need to design how we handler the `retryMessageOperation` callback for different operations.

We discussed in today's standup and decided the retry operation will be look like this

```
retryMessageOperation(Operation object, new MessageOperationCallback() {
    void onSuccess(Operation object, Message message) {
    }

   void onFail(Error error) {
    }
})
```

A new generic MessageOperationCallback will be called after retry the operation.

**Comment by carmenlau** [comment]
The behavior is confirmed and have actionable issues.
