### ISSUE TITLE
[UIKit] Incorrect image orientation when the photo is in delivering state

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/chat-SDK-Android#161]
Checked and confirmed the both thumbnail and image orientation is correct in server. The image orientation is wrong in the delivering state. So when user upload a image, the image will first show an incorrect orientation. After it is uploaded and the app download the image from remote, the orientation will be correct.

**Comment by howawong** [comment]
Sounds like picasso  cannot handle EXIF well
https://github.com/square/picasso/pull/692
