### ISSUE TITLE
Unable to create conversation on Android 4.3

### ISSUE THREAD

**Issue by cpryanpang** [SkygearIO/chat-SDK-Android#17]
Call to `ChatContainer#createConversation(...)` failed, when `participant_ids` and `admin_ids` are set as same values (2 users' IDs).

The plugin codes adopted are at commit @5584c24 .

**Comment by ben181231** [comment]
We have identified the issue and updated. Please help to check whether the commit 761ba6b can fix the issue.

**Comment by cpryanpang** [comment]
Thank you @ben181231. We are having test on it.
