### ISSUE TITLE
MessageSubscriptionCallback has unexposed useful constants.

### ISSUE THREAD

**Issue by cpryanpang** [SkygearIO/chat-SDK-Android#18]
(Following comments are targeted on commit 761ba6b)

There are 3 defined constants of **event type** in [MessageSubscriptionCallback.java#L14](https://github.com/SkygearIO/chat-SDK-Android/blob/master/chat/src/main/java/io/skygear/plugins/chat/MessageSubscriptionCallback.java#L14)

```
    static final String[] SUPPORTED_EVENT_TYPES = new String[]{
            "create",
            "update",
            "delete"
    };
```

It is unwise for us (plugin user) to hard code the event type `"create"` or `"update"` when we use the `ChatContainer.subscribeConversationMessage`, as demonstrated at [ConversationActivity.kt#L210](https://github.com/SkygearIO/chat-SDK-Android/blob/master/chat_example/src/main/java/io/skygear/chatexample/ConversationActivity.kt#L210)

Please justify whether below change is appropriate:
```
public abstract class MessageSubscriptionCallback implements SubscriptionCallback {

    public static final String EVENT_TYPE_CREATE = "create";
    public static final String EVENT_TYPE_UPDATE = "update";
    public static final String EVENT_TYPE_DELETE = "delete";

    static final String[] SUPPORTED_EVENT_TYPES = new String[]{
        EVENT_TYPE_CREATE,
        EVENT_TYPE_UPDATE,
        EVENT_TYPE_DELETE,
    };

    ...
}
```

**Comment by ben181231** [comment]
Seems great. Let me make it public.
