### ISSUE TITLE
Support automaticallyMarkMessageAsDelivered

### ISSUE THREAD

**Issue by royuen** [SkygearIO/chat-SDK-Android#20]
- [ ] Support automaticallyMarkMessageAsDelivered
Similar to http://cocoadocs.org/docsets/SKYKitChat/0.0.1/Classes/SKYChatExtension.html#//api/name/markDeliveredMessages:completion:NS_SWIFT_NAME:

**Comment by chpapa** [comment]
@howawong @carmenlau did we support it now?

**Comment by rickmak** [comment]
We already mark the message as delivered automatically: https://github.com/SkygearIO/chat-SDK-Android/blob/master/chat/src/main/java/io/skygear/plugins/chat/ChatContainer.java#L639
