### ISSUE TITLE
[UIKit] Configuration of Conversation View

### ISSUE THREAD

**Issue by royuen** [SkygearIO/chat-SDK-Android#23]
I'm aggregating the settings of Conversation View here.

I think we need to design a way so that configuration is easy to set. Top of my head it could be done by:

* Constructor configurations + Setter
* Callback Function

I think different config might be better to use a different way to configure? Or we should just use app delegate? (However, I think it is weird to use app delegate to set simple things like the color?)

Also, don't assume all Conversation View in the apps have the same setting. (e.g. Users might want Read by enabled only for certain users).

Anyway, here are a list:

## Feature Enable
* Disable / Enable Voice Message
* ~~Disable / Enable Sending Attachment~~
* Disable / Enable Sending Camera Images
* Disable / Enable Read Status
* Disable / Enable Typing Indicator

## UI Customization
* Bubble incoming background color
* Bubble incoming text color
* Bubble incoming voice play button color
* Bubble incoming timestamp color

* Bubble outgoing background color
* Bubble outgoing text color
* Bubble outgoing status text color
* Bubble outgoing voice play button color
* Bubble outgoing timestamp color

* Conversion background color
* Conversion background drawable (for local image)
* Conversion background images url (for remote image)

* Copywriting Customization #101 

* ~~Text Area Background Color~~
* ~~Icons of Attachment, Camera, and Voice Message~~

## Behaviour Customization
* Show Group Title or Other Username's as Group name #102

## Event Hook Callback #103 
* New Message in Conversation View
* Updated Message in Conversation View
* Before / After Message Send
* Message Send Failed
* Disconnected
* Connected

**Comment by ben181231** [comment]
I will try to build the UIKit using [3rd party ChatKit](https://github.com/stfalcon-studio/ChatKit).

**Comment by carmenlau** [comment]
- [ ] Prepare a list of configurable items based on [chatkit](https://github.com/stfalcon-studio/ChatKit)

**Comment by ben181231** [comment]
@carmenlau 
I have prepared a list of features implemented in Chat UIKit on iOS. Most of them are connecting UI with Skygear Chat. For the UI configurable items, I think they can implemented in ChatKit.

I think the following list can be the specification of the Android UIKit for Skygear Chat.

### Conversation View

#### UI
- Message Bubble Color
- Message Avatar
- Typing Indicator
- Accessory Button Should Show
- Accessory Button Action

#### Skygear Chat Features
- Message Status (all read / some read / sent / delivering)
- Typing Indicator
- Participants Fetching
- Messages Fetching
- Message Change Subscription

#### Hooks
- Before Message Send Hook
- After Message Send Hook
- Failed to Send Message Hook
- After Fetch Participants Hook
- Failed to Fetch Participants Hook
- Before Fetch Message Hook
- After Fetch Message Hook
- Failed to Fetch Message Hook

### Conversation List View

#### UI
- Conversation Avatar
- Pull Down Refresh

#### Skygear Chat Features
- Conversation Change Subscription
- Conversation Unread Count Badge
- Conversation Last Message

### Participant List View

#### UI
- Conversation Avatar

#### Skygear Chat Features
- Query Participants (by username, by name, by email)

**Comment by carmenlau** [comment]
The design of chat ui

https://www.dropbox.com/s/dmvuxxon49fo646/SkygearChatApp%28Android%29-130917.png?dl=0
https://www.dropbox.com/s/y72t5pwm8xr7dlg/Android-SkygearChatApp-170817.sketch?dl=0

**Comment by carmenlau** [comment]
## Feature Enable
* Disable / Enable Voice Message
* Disable / Enable Sending Camera Images
* ~~Disable / Enable Sending Attachment~~
* Disable / Enable Read Status
* Disable / Enable Typing Indicator

## UI Customization
* Bubble incoming background color
* Bubble incoming text color
* Bubble incoming voice play button color
* Bubble incoming timestamp color

* Bubble outgoing background color
* Bubble outgoing text color
* Bubble outgoing status text color
* Bubble outgoing voice play button color
* Bubble outgoing timestamp color

* Conversion background color
* Conversion background images

* Show Group Title or Other Username's as Group name #80 
* ~~Text Area Background Color~~
* ~~Icons of Attachment, Camera, and Voice Message~~

## Behaviour Customization
* Copywriting Customization #39 

## Event Hook Callback
* New Message in Conversation View
* Updated Message in Conversation View
* Before / After Message Send
* Message Send Failed
* Disconnected
* Connected

**Comment by carmenlau** [comment]
- New Message in Conversation View
- Updated Message in Conversation View
- Before / After Message Send
- Message Send Failed
- Disconnected
- Connected

**Comment by howawong** [comment]
Hi, Disconnect and Connect cannot be done in Android and iOS because there is no listener to hook with PubsubContainer, only JS has such feature.

skygeario/skygear-SDK-Android#173
skygeario/skygear-SDK-iOS#155
