### ISSUE TITLE
Edit message should support update of metadata and asset 

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/chat-SDK-Android#31]

**Comment by howawong** [comment]
What if new metadata/asset is null, shall i consider it is emptying asset/metadata or keeping it unchanged?

**Comment by chpapa** [comment]
@howawong maybe should have function overload? So if users don't want to update metadata / asset they should skip them? Or any idea?

**Comment by carmenlau** [comment]
Please also check if ios support update message meta data
