### ISSUE TITLE
Publish to mavenCentral or jcenter

### ISSUE THREAD

**Issue by omainegra** [SkygearIO/chat-SDK-Android#38]
The last published version is `0.0.1` which seems to be incompatible with `skygear:1.1.0`, please publish as soon as you can.

**Comment by rickmak** [comment]
We have released `1.1.2` yesterday on maven refs: https://bintray.com/skygeario/maven/skygear-chat-android

You can add this line in your gradle file to use the latest chat plugin: `compile 'io.skygear.plugins:chat:1.1.2'`
