### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by royuen** [SkygearIO/chat-SDK-Android#5]

**Comment by kaojohnny** [comment]
[chat.zip](https://github.com/SkygearIO/chat-SDK-Android/files/523960/chat.zip)

**Comment by kaojohnny** [comment]
[chat.zip](https://github.com/SkygearIO/chat-SDK-Android/files/524102/chat.zip)

**Comment by rickmak** [comment]
@kaojohnny Please let @ben181231 know the build command and he will put the build at travis.yml and travis will upload the doc to s3 on push to master.

Please also add the link to README.md ocne the URL ready.

**Comment by kaojohnny** [comment]
@ben181231 You can use `./gradlew :chat:generateJavadocs` to generate Javadoc, the result will be under `chat/build/docs/javadoc/`

**Comment by ben181231** [comment]
Done in Commit 8a98184
