### ISSUE TITLE
[UIKit] Avatar field should be asset instead of string

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/chat-SDK-Android#61]
We also need to check in iOS uikit the avatar is string or asset? They need to be the same.

**Comment by chpapa** [comment]
@carmenlau Actually I think it is better to be configurable as mentioned in skygeario/chat-sdk-ios#95

Details:

1. Specific avatar by:
    1. Which field in the User Record is the Asset field to the avatar, or
    1. Which field in the User Record is the URL to the avatar, or
    1. AppDelegate to resolve the Avatar, from the Message object
1. Specific a default avatar, which will show if the field in User Record is empty or null,
    1. An Image object in native platform, or
    1. Default generator pick two letters in the username to show an icon like "BC" (Ben Cheng)
    1. AppDelegate are supposed to handle default avatar on its own.

**Comment by chpapa** [comment]
Should handle at #69
