### ISSUE TITLE
[UIKit] Allow config user fields for display name and avatar

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/chat-SDK-Android#69]
Current default:
Display name: name (String)
Display avatar: avatar (Asset)

Need support config using another fields

**Comment by chpapa** [comment]
@carmenlau @ben181231 

Actually I think it is better to be configurable as mentioned in skygeario/chat-sdk-ios#95

Details:

1. Specific avatar by:
    1. Which field in the User Record is the Asset field to the avatar, or
    1. Which field in the User Record is the URL to the avatar, or
    1. AppDelegate to resolve the Avatar, from the Message object
1. Specific a default avatar, which will show if the field in User Record is empty or null,
    1. An Image object in native platform, or
    1. Default generator pick two letters in the username to show an icon like "BC" (Ben Cheng)
    1. AppDelegate are supposed to handle default avatar on its own.

**Comment by carmenlau** [comment]
AttributeSet in constructor, XML
    - avatar
    - avatarType
adaptor factory
    - return View

**Comment by rickmak** [comment]
Improved list of config after offline discussion (@carmenlau, @howawong, @ben181231, @Steven-Chan, @cheungpat )

- Customization via AttributeSet/XML
  - Background color
  - Initial text color
  - Sender text color
  - avatar
  - avatarType
  - username field
  - Show hide Sender / Receiver
- adaptor factory
    - accept conversation, message, author -> return View (Example rainbow bg color in group chat)
    - Show hide Sender / Receiver

**Comment by howawong** [comment]
Sample Layout XML

```xml
<?xml version="1.0" encoding="utf-8"?>
<io.skygear.plugins.chat.ui.ConversationView
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    uikit:avatarNameField="email"
    uikit:avatarImageField="avatar"
    uikit:avatarShowSender="true"
    uikit:avatarShowReceiver="true"
    uikit:senderUserNameTextColor="@color/cornflower_blue_light_40"
    uikit:avatarBackgroundColor="@color/common_google_signin_btn_text_light"
    uikit:avatarInitialTextColor="@color/white"
    uikit:avatarType="initial"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:uikit="http://schemas.android.com/apk/res-auto"/>
```

**Comment by carmenlau** [comment]
When handling username display, please remember to check the setting is applied to all message type. All messages type should show the sender name. Thanks!

**Comment by carmenlau** [comment]
@howawong Would like to align the variable name among iOS and android. Please update using following. Thanks!!

avatarBackgroundColor: UIColor?
avatarTextColor: UIColor?
messageSenderTextColor: UIColor?
avatarHiddenForOutgoingMessages: Bool = false
avatarHiddenForIncomingMessages: Bool = false
userNameField
userAvatarField
userAvatarType

**Comment by carmenlau** [comment]
Please update the attribute name
