### ISSUE TITLE
[ChatContainer] JsonObject retrieves Optionkeys instead of String

### ISSUE THREAD

**Issue by spmvanmierlo** [SkygearIO/chat-SDK-Android#75]
Hi,

When calling 'createDirectConversation' I get a error: 
"Caused by: java.lang.ClassCastException: io.skygear.plugins.chat.Conversation$OptionKey cannot be cast to java.lang.String"

My guess is that the JSONObject (at line: 97 of the ChatContainer class) in the 'createConversation' method is expecting a String in his constructor instead of the OptionKey from the enum.

Correct me if I am wrong! Look forward to a fix.

**Comment by carmenlau** [comment]
@spmvanmierlo Thanks for reporting! Yes, there is some problem in `createDirectConversation`. We already created an issue https://github.com/SkygearIO/chat-SDK-Android/issues/68 for that. Will fix it very soon and update in the coming release. :)

**Comment by chpapa** [comment]
Fix on #68
